// <auto-generated />
namespace UniOdonto.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _160620201904 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_160620201904));
        
        string IMigrationMetadata.Id
        {
            get { return "202006170005328_160620201904"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
