// <auto-generated />
namespace UniOdonto.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _240620202137 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_240620202137));
        
        string IMigrationMetadata.Id
        {
            get { return "202006250241352_240620202137"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
