// <auto-generated />
namespace UniOdonto.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _190720201313 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_190720201313));
        
        string IMigrationMetadata.Id
        {
            get { return "202007191816439_190720201313"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
